config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('search/', include('search.urls'), name='search'),
    path('admin/', admin.site.urls),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

search/urls.py
from django.urls import path

from . import views

app_name = 'search'

urlpatterns = [
    path('', views.index, name='index'),
    path('days_buyer/', views.days_buyer, name='days_buyer'),
    path('class_buyer_and_newsletter/', views.class_buyer_and_newsletter, name='class_buyer_and_newsletter'),
    path('class_not_buyer_with_address/', views.class_not_buyer_with_address, name='class_not_buyer_with_address'),
    path('link_price_partial_cancel/', views.link_price_partial_cancel, name='link_price_partial_cancel'),
    path('first_buyer_count_month/', views.first_buyer_count_month, name='first_buyer_count_month'),
    path('re_buy_percentage/', views.re_buy_percentage, name='re_buy_percentage'),
    path('end_subscribe_count_monthly/', views.end_subscribe_count_monthly, name='end_subscribe_count_monthly'),
    path('subscribe_extension_count_monthly/', views.subscribe_extension_count_monthly, name='subscribe_extension_count_monthly'),
    path('join_user_count/', views.join_user_count, name='join_user_count'),
    path('join_month_next_month_buyer_count/', views.join_month_next_month_buyer_count, name='join_month_next_month_buyer_count'),
    path('offline_location_clients/', views.offline_location_clients, name='offline_location_clients'),
    path('buy_info_during/', views.buy_info_during, name='buy_info_during'),
    path('sell_product_info/', views.sell_product_info, name='sell_product_info'),
    path('delete_file/', views.delete_file, name='delete_file'),
    path('subscribers_cnt/', views.subscribers_cnt, name='subscribers_cnt'),
    path('invalid_point/', views.invalid_point, name='invalid_point'),
    path('join_user_by_monthly/', views.join_user_by_monthly, name='join_user_by_monthly'),
    path('payment_method_data/', views.payment_method_data, name='payment_method_data'),
    path('product_category_incoming_for_long/', views.product_category_incoming_for_long, name='product_category_incoming_for_long'),
    path('sell_info_about_product_item_code/', views.sell_info_about_product_item_code, name='sell_info_about_product_item_code'),
    path('sell_info_about_product_item_code_subscription/', views.sell_info_about_product_item_code_subscription, name='sell_info_about_product_item_code_subscription'),
    path('sell_info_about_product_item_code_regular_payment/', views.sell_info_about_product_item_code_regular_payment, name='sell_info_about_product_item_code_regular_payment'),
    # path('user/', views.search_user, name='user'),
    # path('buyer_count/', views.search_buyer_count_days, name='buyer_count'),
    # path('class_buyer_and_newsletter/', views.search_class_buyer_and_newsletter, name='class_buyer_and_newsletter')
]

search/models.py
from django.db import models

# Create your models here.

search/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.template import loader

from exceptions.CommonException import CommonException
from . import repository
from . import utils


def call_return(req, template, name, success, message=''):
    folder, files = utils.file_list_and_dir(name)
    context = {'success': success, 'message': message, 'folder': folder, 'files': files}
    return HttpResponse(template.render(context, req))


def call_return_with_data(req, template, name, success, data='', message=''):
    folder, files = utils.file_list_and_dir(name)
    context = {'success': success, 'message': message, 'data': data, 'folder': folder, 'files': files}
    return HttpResponse(template.render(context, req))


def index(req):
    """ home page"""

    template = loader.get_template('search/index.html')
    context = {}
    return HttpResponse(template.render(context, req))


def delete_file(req):
    """ 파일 삭제 """
    folder = req.GET.get('folder')
    file = req.GET.get('file')
    template = req.GET.get('template')
    utils.remove_file(folder+'/'+file)

    #print(template)
    return redirect(template)


def class_not_buyer_with_address(req):

    name = 'class_not_buyer_with_address'
    template = loader.get_template('search/'+name+'/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    start = req.GET.get('start')
    address = req.GET.get('search_word')

    try:
        repository.search_not_buy_class_and_address(start, address)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)

    return redirect('search:'+name)


def sell_product_info(req):
    """판매 상품 조회"""
    name = 'sell_product_info'
    template = loader.get_template('search/'+name+'/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    start = req.GET.get('start')
    p_name = req.GET.get('search_word')

    try:
        repository.sell_product_info(p_name, start)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)

    return redirect('search:'+name)


def class_buyer_and_newsletter(req):
    """클래스 구매고객 (뉴스레터 동의)"""

    name = 'class_buyer_and_newsletter'
    template = loader.get_template('search/'+name+'/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    try:
        repository.search_class_buyer_and_newsletter()
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def days_buyer(req):
    """기간내 구매자 조회 페이지 """

    name = 'days_buyer'
    template = loader.get_template('search/'+name+'/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    start = req.GET.get('start')
    end = req.GET.get('end')

    try:
        repository.search_days_buyer(start, end)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def join_user_by_monthly(req):
    """회원가입자 수를 월별로 조회"""

    name = 'join_user_by_monthly'
    template = loader.get_template('search/'+name+'/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    start = req.GET.get('start')
    end = req.GET.get('end')

    try:
        repository.join_user_by_monthly(start, end)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def link_price_partial_cancel(req):
    """ 링크 프라이스 부분취소 금액 확인"""

    name = 'link_price_partial_cancel'
    template = loader.get_template('search/'+name+'/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    order_code_list = req.GET.get('text_input')

    try:
        repository.link_price_partial_cancel(order_code_list)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def first_buyer_count_month(req):
    """카테고리 첫구매자수"""
    name = 'first_buyer_count_month'
    template = loader.get_template('search/' + name + '/index.html')

    search = req.GET.get('search')

    try:
        data = repository.product_category_list()
    except CommonException as a:
        return call_return(req, template, name, False, a.message)

    if search != '1':
        return call_return_with_data(req, template, name, True, data)

    product_category_list = req.GET.getlist('product_category')
    include = req.GET.get('is_include')

    is_member = -1 # req.GET.get('is_member')

    try:
        repository.first_buyer_count_month(product_category_list, include, is_member)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def product_category_incoming_for_long(req):
    """카테고리 첫구매자수"""
    name = 'product_category_incoming_for_long'
    template = loader.get_template('search/' + name + '/index.html')

    search = req.GET.get('search')

    try:
        data = repository.product_category_list()
    except CommonException as a:
        return call_return(req, template, name, False, a.message)

    if search != '1':
        return call_return_with_data(req, template, name, True, data)

    product_category_list = req.GET.getlist('product_category')
    include = req.GET.get('is_include')

    start = req.GET.get('start')
    end = req.GET.get('end')

    try:
        repository.product_category_incoming_for_long(product_category_list, include, start, end)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def re_buy_percentage(req):
    """재구매율"""

    name = 're_buy_percentage'
    template = loader.get_template('search/' + name + '/index.html')

    try:
        data = repository.product_category_list()
    except CommonException as a:
        return call_return(req, template, name, False, a.message)

    search = req.GET.get('search')

    if search != '1':
        return call_return_with_data(req, template, name, True, data)

    product_category_list = req.GET.getlist('product_category')

    include = req.GET.get('is_include')

    try:
        repository.re_buy_percentage(product_category_list, include)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def end_subscribe_count_monthly(req):
    """구독종료예정 수 조회"""

    name = 'end_subscribe_count_monthly'
    template = loader.get_template('search/' + name + '/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    start_date = req.GET.get('date')
    try:
        repository.end_subscribe_count_monthly(start_date)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def subscribe_extension_count_monthly(req):
    """구독종료예정 수 조회"""

    name = 'subscribe_extension_count_monthly'
    template = loader.get_template('search/' + name + '/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    start_date = req.GET.get('date')
    try:
        repository.subscribe_extension_count_monthly(start_date)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def join_user_count(req):
    """회원가입자수 조회"""

    name = 'join_user_count'
    template = loader.get_template('search/' + name + '/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    start = req.GET.get('start')
    end = req.GET.get('end')
    is_anony = 'TRUE' if len(req.GET.getlist('check_01')) > 0 else 'FALSE'
    is_non_registered = 'TRUE' if len(req.GET.getlist('check_02')) > 0 else 'FALSE'

    try:
        repository.join_user_count(start, end, is_anony, is_non_registered)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def join_month_next_month_buyer_count(req):
    """회원가입자수 조회"""

    name = 'join_month_next_month_buyer_count'
    template = loader.get_template('search/' + name + '/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    date = req.GET.get('date')
    try:
        repository.join_month_next_month_buyer_count(date)
        return redirect('search:'+name)
    except CommonException as a:
        return call_return(req, template, name, False, a.message)


def offline_location_clients(req):
    """오프라인 특정지역 고객데이터 조회"""

    name = 'offline_location_clients'
    template = loader.get_template('search/' + name + '/index.html')

    search = req.GET.get('search')
    if search != '1':
        return call_return(req, template, name, True)

    locations = req.GET.get('locations')
    not_include_location = req.GET.get('not_include_location')
    is_buyer_for_days = req.GET.get('is_buyer_for_days')
    start = req.GET.get('start')
    end = req.GET.get('end')
    try:
        repository.offline_location_clients(locations, not_include_location, is_buyer_for_days, start, end)
        return redirect('search:' + name)
    except CommonException as a:

search/templates/search/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="{% static 'css/bootstrap.css' %}" rel="stylesheet" crossorigin="anonymous"/>
</head>
<body>
    <div class="container">
        <div class="alert alert-success m-2" style="text-align: center">꾸까 데이터 조회</div>
        <table class="table table-striped">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        title
                    </th>
                    <th>
                        비고
                    </th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td><a href="{%  url 'search:days_buyer'%}">기간내 구매자수 조회</a></td>
                    <td>요청하는 기간내에 구매자수를 반환</td>
                </tr>
                <tr>
                    <th scope="row">2</th>
                    <td><a href="{%  url 'search:class_buyer_and_newsletter'%}">클래스 고객데이터 요청(클래스구매고객, 뉴스레터동의)</a></td>
                    <td>클래스구매 고객리스트(뉴스레터동의)</td>
                </tr>
                <tr>
                    <th scope="row">3</th>
                    <td><a href="{%  url 'search:class_not_buyer_with_address'%}">클래스를 구매하지 않은 고객(뉴스레터동의, 특정기간이후, 특정주소지)</a></td>
                    <td>클래스를 구매하지 않은 고객리스트(뉴스레터동의, 특정기간이후, 특정주소지)</td>
                </tr>
                <tr>
                    <th scope="row">4</th>
                    <td><a href="{%  url 'search:link_price_partial_cancel'%}">링크프라이스 부분취소 금액확인</a></td>
                    <td>order code List를 입력하여 해당 order code의 부분취소 금액을 확인</td>
                </tr>
                <tr>
                    <th scope="row">5</th>
                    <td><a href="{%  url 'search:first_buyer_count_month'%}">첫구매자수를 월별로 조회</a></td>
                    <td>월별로 첫구매자수를 조회</td>
                </tr>
                <tr>
                    <th scope="row">6</th>
                    <td><a href="{%  url 'search:re_buy_percentage'%}">현재까지 월별 재구매율 조회</a></td>
                    <td>현재까지 월별 재구매율을 조회</td>
                </tr>
                <tr>
                    <th scope="row">7</th>
                    <td><a href="{%  url 'search:end_subscribe_count_monthly'%}">원하는 날짜부터 현재까지 월별 구독종료 예정수</a></td>
                    <td>원하는 날짜부터 현재까지 월별 구독종료 예정수 조회</td>
                </tr>
                <tr>
                    <th scope="row">8</th>
                    <td><a href="{%  url 'search:subscribe_extension_count_monthly'%}">원하는 날짜부터 현재까지 월별 구독 연장수</a></td>
                    <td>원하는 날짜부터 현재까지 월별 구독 연장수 조회</td>
                </tr>
                <tr>
                    <th scope="row">9</th>
                    <td><a href="{%  url 'search:join_user_count'%}">회원가입자수 조회</a></td>
                    <td>기간내 회원가입자수 조회</td>
                </tr>
                <tr>
                    <th scope="row">10</th>
                    <td><a href="{%  url 'search:join_month_next_month_buyer_count'%}">선택월, 그 다음월 구매자수</a></td>
                    <td>해당월을 넣으면 해당월/ 그다음월 구매자수 조회</td>
                </tr>
                <tr>
                    <th scope="row">11</th>
                    <td><a href="{%  url 'search:offline_location_clients'%}">오프라인 특정지역 고객데이터 조회</a></td>
                    <td>뉴스레터 수신동의/특정기간 꽃배송구매자/지역/포함안되는지역명 조건으로 조회(이름, 전화번호, 주소(시, 구까지), 성별, 회원등급)</td>
                </tr>
                <tr>
                    <th scope="row">12</th>
                    <td><a href="{%  url 'search:buy_info_during'%}">특정기간동안 구매자 및 구매정보 조회</a></td>
                    <td>사용자아이디, 주문아이디, 주문번호, 전체구매횟수, 전화, 이메일, 뉴스레터, box_code, 새벽배송</td>
                </tr>
                <tr>
                    <th scope="row">13</th>
                    <td><a href="{%  url 'search:sell_product_info'%}">특정일자 기준으로 상풍코드로 판매리스트 조회</a></td>
                    <td>사용자아이디, 주문번호, 상품이름, 상품코드, 박스옵션, 카테고리번호, 카테고리이름, 총금액, 결제금액</td>
                </tr>
                <tr>
                    <th scope="row">14</th>
                    <td><a href="{%  url 'search:subscribers_cnt'%}">특정일자 기준으로 구독자 조회</a></td>
                    <td>상품명, 상품 코드, box_option_name, box_type, 구독자수</td>
                </tr>
                <tr>
                    <th scope="row">15</th>
                    <td><a href="{%  url 'search:invalid_point'%}">특정일 기준으로 삭제포인트 조회</a></td>
                    <td>사용자아이디, 이메일, 연락처, 포인트아이디, 기준일이전 포인트, 기준일이후 포인트, 사용포인트, 남은포인트, 삭제할포인트</td>
                </tr>
                <tr>
                    <th scope="row">16</th>
                    <td><a href="{%  url 'search:join_user_by_monthly'%}">회원가입자 수를 일별로 조회</a></td>
                    <td>날짜, 전체가입자, 외부채널/b2b 가입자, 비회원구매가입자, 순수회원가입자</td>
                </tr>
                <tr>
                    <th scope="row">17</th>
                    <td><a href="{%  url 'search:product_category_incoming_for_long'%}">카테고리별 월별 매출 조회</a></td>
                    <td>년월, 매출액</td>
                </tr>
                <tr>
                    <th scope="row">18</th>
                    <td><a href="{%  url 'search:payment_method_data'%}">결제방법별 매출액 및 결제건수 조회</a></td>
                    <td>결제타입,매출액, 거래건수</td>
                </tr>
                <tr>
                    <th scope="row">19</th>
                    <td><a href="{%  url 'search:sell_info_about_product_item_code'%}">아이템코드로 판매정보 조회하기</a></td>
                    <td>판매수량	판매가(상품 비용)	할인금액(등급할인+포인트할인+코드할인)	배송비	최종지불금액</td>
                </tr>
                <tr>
                    <th scope="row">20</th>
                    <td><a href="{%  url 'search:sell_info_about_product_item_code_subscription'%}">정기구독 아이템코드로 판매정보 조회하기</a></td>
                    <td>판매수량	판매가(상품 비용)	할인금액(등급할인+포인트할인+코드할인)	배송비	최종지불금액</td>
                </tr>
                <tr>
                    <th scope="row">21</th>
                    <td><a href="{%  url 'search:sell_info_about_product_item_code_regular_payment'%}">정기결제 아이템코드로 판매정보 조회하기</a></td>
                    <td>판매수량	판매가(상품 비용)	할인금액(등급할인+포인트할인+코드할인)	배송비	최종지불금액</td>
                </tr>
            </tbody>

        </table>
    </div>

</body>
</html>